# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 819)
        icon = QtGui.QIcon.fromTheme("SP_ComputerIcon")
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(0, 0, 1001, 771))
        self.Tabs.setObjectName("Tabs")
        self.Main = QtWidgets.QWidget()
        self.Main.setObjectName("Main")
        self.groupBox = QtWidgets.QGroupBox(self.Main)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 991, 291))
        self.groupBox.setObjectName("groupBox")
        self.commands_file_edit = QtWidgets.QLineEdit(self.groupBox)
        self.commands_file_edit.setGeometry(QtCore.QRect(30, 60, 711, 21))
        self.commands_file_edit.setText("")
        self.commands_file_edit.setObjectName("commands_file_edit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 241, 20))
        self.label.setObjectName("label")
        self.get_commands_file_button = QtWidgets.QPushButton(self.groupBox)
        self.get_commands_file_button.setGeometry(QtCore.QRect(880, 50, 81, 41))
        self.get_commands_file_button.setObjectName("get_commands_file_button")
        self.create_commands_file_button = QtWidgets.QPushButton(self.groupBox)
        self.create_commands_file_button.setGeometry(QtCore.QRect(770, 50, 81, 41))
        self.create_commands_file_button.setObjectName("create_commands_file_button")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 241, 20))
        self.label_2.setObjectName("label_2")
        self.gesture_box = QtWidgets.QComboBox(self.groupBox)
        self.gesture_box.setGeometry(QtCore.QRect(30, 110, 231, 101))
        self.gesture_box.setMaxVisibleItems(5)
        self.gesture_box.setIconSize(QtCore.QSize(100, 100))
        self.gesture_box.setObjectName("gesture_box")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/like.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/dislike.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/one.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/peace.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/peace_inverted.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/three.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/four.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/palm.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/grabbing.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/fist.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon9, "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/grip.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon10, "")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/point.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon11, "")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/three3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon12, "")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/three2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon13, "")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/little_finger.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon14, "")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/middle_finger.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon15, "")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icons/ok.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon16, "")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("icons/rock.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon17, "")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("icons/call.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon18, "")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("icons/stop.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon19, "")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("icons/stop_inverted.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon20, "")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("icons/two_up.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon21, "")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("icons/two_up_inverted.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon22, "")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("icons/three_gun.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon23, "")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("icons/thumb_index.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon24, "")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("icons/thumb_index2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon25, "")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("icons/holy.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon26, "")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("icons/timeout.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon27, "")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap("icons/xsign.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon28, "")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap("icons/hand_heart.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon29, "")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("icons/hand_heart2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon30, "")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap("icons/take_picture.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon31, "")
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap("icons/mute.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gesture_box.addItem(icon32, "")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(340, 120, 231, 16))
        self.label_3.setObjectName("label_3")
        self.script_path_edit = QtWidgets.QLineEdit(self.groupBox)
        self.script_path_edit.setGeometry(QtCore.QRect(340, 150, 511, 21))
        self.script_path_edit.setText("")
        self.script_path_edit.setObjectName("script_path_edit")
        self.get_script_file_button = QtWidgets.QPushButton(self.groupBox)
        self.get_script_file_button.setGeometry(QtCore.QRect(880, 140, 81, 41))
        self.get_script_file_button.setObjectName("get_script_file_button")
        self.save_command_button = QtWidgets.QPushButton(self.groupBox)
        self.save_command_button.setGeometry(QtCore.QRect(250, 230, 151, 41))
        self.save_command_button.setObjectName("save_command_button")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(280, 130, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_24.setFont(font)
        self.label_24.setLineWidth(2)
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.delete_commands_button = QtWidgets.QPushButton(self.groupBox)
        self.delete_commands_button.setGeometry(QtCore.QRect(610, 230, 151, 41))
        self.delete_commands_button.setObjectName("delete_commands_button")
        self.show_commands_button = QtWidgets.QPushButton(self.groupBox)
        self.show_commands_button.setGeometry(QtCore.QRect(430, 230, 151, 41))
        self.show_commands_button.setObjectName("show_commands_button")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Main)
        self.groupBox_2.setGeometry(QtCore.QRect(-1, 289, 991, 471))
        self.groupBox_2.setObjectName("groupBox_2")
        self.main_chkpt_file_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.main_chkpt_file_edit.setGeometry(QtCore.QRect(280, 50, 571, 21))
        self.main_chkpt_file_edit.setText("")
        self.main_chkpt_file_edit.setObjectName("main_chkpt_file_edit")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(280, 30, 231, 16))
        self.label_4.setObjectName("label_4")
        self.get_main_chkpt_button = QtWidgets.QPushButton(self.groupBox_2)
        self.get_main_chkpt_button.setGeometry(QtCore.QRect(880, 40, 81, 41))
        self.get_main_chkpt_button.setObjectName("get_main_chkpt_button")
        self.main_model_type_box = QtWidgets.QComboBox(self.groupBox_2)
        self.main_model_type_box.setGeometry(QtCore.QRect(40, 50, 191, 22))
        self.main_model_type_box.setObjectName("main_model_type_box")
        self.main_model_type_box.addItem("")
        self.main_model_type_box.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(40, 30, 231, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(470, 140, 71, 16))
        self.label_7.setObjectName("label_7")
        self.main_confidence_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.main_confidence_edit.setGeometry(QtCore.QRect(400, 160, 231, 21))
        self.main_confidence_edit.setCursorPosition(3)
        self.main_confidence_edit.setObjectName("main_confidence_edit")
        self.main_iou_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.main_iou_edit.setGeometry(QtCore.QRect(710, 160, 231, 21))
        self.main_iou_edit.setCursorPosition(3)
        self.main_iou_edit.setObjectName("main_iou_edit")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(820, 140, 31, 20))
        self.label_8.setObjectName("label_8")
        self.main_camera_box = QtWidgets.QComboBox(self.groupBox_2)
        self.main_camera_box.setGeometry(QtCore.QRect(40, 160, 191, 22))
        self.main_camera_box.setObjectName("main_camera_box")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(40, 140, 231, 16))
        self.label_6.setObjectName("label_6")
        self.start_app_button = QtWidgets.QPushButton(self.groupBox_2)
        self.start_app_button.setGeometry(QtCore.QRect(410, 300, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_app_button.setFont(font)
        self.start_app_button.setObjectName("start_app_button")
        self.Tabs.addTab(self.Main, "")
        self.Data = QtWidgets.QWidget()
        self.Data.setObjectName("Data")
        self.label_9 = QtWidgets.QLabel(self.Data)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 151, 16))
        self.label_9.setObjectName("label_9")
        self.data_save_folder_edit = QtWidgets.QLineEdit(self.Data)
        self.data_save_folder_edit.setGeometry(QtCore.QRect(10, 40, 811, 22))
        self.data_save_folder_edit.setObjectName("data_save_folder_edit")
        self.get_data_save_folder_button = QtWidgets.QPushButton(self.Data)
        self.get_data_save_folder_button.setGeometry(QtCore.QRect(850, 30, 81, 41))
        self.get_data_save_folder_button.setObjectName("get_data_save_folder_button")
        self.data_camera_box = QtWidgets.QComboBox(self.Data)
        self.data_camera_box.setGeometry(QtCore.QRect(250, 90, 191, 22))
        self.data_camera_box.setObjectName("data_camera_box")
        self.label_10 = QtWidgets.QLabel(self.Data)
        self.label_10.setGeometry(QtCore.QRect(250, 70, 231, 16))
        self.label_10.setObjectName("label_10")
        self.get_photo_button = QtWidgets.QPushButton(self.Data)
        self.get_photo_button.setEnabled(False)
        self.get_photo_button.setGeometry(QtCore.QRect(450, 670, 121, 41))
        self.get_photo_button.setObjectName("get_photo_button")
        self.timer_edit = QtWidgets.QLineEdit(self.Data)
        self.timer_edit.setGeometry(QtCore.QRect(360, 680, 71, 22))
        self.timer_edit.setObjectName("timer_edit")
        self.label_14 = QtWidgets.QLabel(self.Data)
        self.label_14.setGeometry(QtCore.QRect(300, 680, 51, 16))
        self.label_14.setObjectName("label_14")
        self.use_camera_button = QtWidgets.QPushButton(self.Data)
        self.use_camera_button.setEnabled(True)
        self.use_camera_button.setGeometry(QtCore.QRect(560, 80, 131, 41))
        self.use_camera_button.setObjectName("use_camera_button")
        self.groupBox_7 = QtWidgets.QGroupBox(self.Data)
        self.groupBox_7.setGeometry(QtCore.QRect(180, 130, 681, 531))
        self.groupBox_7.setObjectName("groupBox_7")
        self.data_image_label = QtWidgets.QLabel(self.groupBox_7)
        self.data_image_label.setGeometry(QtCore.QRect(19, 30, 640, 480))
        self.data_image_label.setText("")
        self.data_image_label.setObjectName("data_image_label")
        self.cancel_photo_button = QtWidgets.QPushButton(self.Data)
        self.cancel_photo_button.setEnabled(False)
        self.cancel_photo_button.setGeometry(QtCore.QRect(600, 670, 121, 41))
        self.cancel_photo_button.setObjectName("cancel_photo_button")
        self.Tabs.addTab(self.Data, "")
        self.Train = QtWidgets.QWidget()
        self.Train.setObjectName("Train")
        self.groupBox_4 = QtWidgets.QGroupBox(self.Train)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 971, 301))
        self.groupBox_4.setObjectName("groupBox_4")
        self.start_train_button = QtWidgets.QPushButton(self.groupBox_4)
        self.start_train_button.setGeometry(QtCore.QRect(410, 230, 131, 41))
        self.start_train_button.setObjectName("start_train_button")
        self.get_data_train_folder_button = QtWidgets.QPushButton(self.groupBox_4)
        self.get_data_train_folder_button.setGeometry(QtCore.QRect(860, 40, 81, 41))
        self.get_data_train_folder_button.setObjectName("get_data_train_folder_button")
        self.train_model_type_box = QtWidgets.QComboBox(self.groupBox_4)
        self.train_model_type_box.setGeometry(QtCore.QRect(20, 100, 191, 22))
        self.train_model_type_box.setObjectName("train_model_type_box")
        self.train_model_type_box.addItem("")
        self.train_model_type_box.addItem("")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(20, 80, 231, 16))
        self.label_16.setObjectName("label_16")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(20, 30, 151, 16))
        self.label_11.setObjectName("label_11")
        self.start_chkpt_file_edit = QtWidgets.QLineEdit(self.groupBox_4)
        self.start_chkpt_file_edit.setGeometry(QtCore.QRect(260, 100, 561, 22))
        self.start_chkpt_file_edit.setObjectName("start_chkpt_file_edit")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(20, 140, 111, 16))
        self.label_17.setObjectName("label_17")
        self.epochs_edit = QtWidgets.QLineEdit(self.groupBox_4)
        self.epochs_edit.setGeometry(QtCore.QRect(20, 160, 101, 22))
        self.epochs_edit.setCursorPosition(1)
        self.epochs_edit.setObjectName("epochs_edit")
        self.get_start_chkpt_file_button = QtWidgets.QPushButton(self.groupBox_4)
        self.get_start_chkpt_file_button.setGeometry(QtCore.QRect(860, 90, 81, 41))
        self.get_start_chkpt_file_button.setObjectName("get_start_chkpt_file_button")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(260, 80, 191, 16))
        self.label_15.setObjectName("label_15")
        self.data_train_edit = QtWidgets.QLineEdit(self.groupBox_4)
        self.data_train_edit.setGeometry(QtCore.QRect(20, 50, 801, 22))
        self.data_train_edit.setObjectName("data_train_edit")
        self.end_chkpt_path_edit = QtWidgets.QLineEdit(self.groupBox_4)
        self.end_chkpt_path_edit.setGeometry(QtCore.QRect(260, 160, 561, 22))
        self.end_chkpt_path_edit.setObjectName("end_chkpt_path_edit")
        self.create_end_chkpt_file_button = QtWidgets.QPushButton(self.groupBox_4)
        self.create_end_chkpt_file_button.setGeometry(QtCore.QRect(860, 150, 81, 41))
        self.create_end_chkpt_file_button.setObjectName("create_end_chkpt_file_button")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(260, 140, 191, 16))
        self.label_23.setObjectName("label_23")
        self.groupBox_5 = QtWidgets.QGroupBox(self.Train)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 310, 971, 441))
        self.groupBox_5.setObjectName("groupBox_5")
        self.test_chkpt_path_edit = QtWidgets.QLineEdit(self.groupBox_5)
        self.test_chkpt_path_edit.setGeometry(QtCore.QRect(20, 80, 801, 22))
        self.test_chkpt_path_edit.setObjectName("test_chkpt_path_edit")
        self.get_test_chkpt_file_button = QtWidgets.QPushButton(self.groupBox_5)
        self.get_test_chkpt_file_button.setGeometry(QtCore.QRect(860, 70, 81, 41))
        self.get_test_chkpt_file_button.setObjectName("get_test_chkpt_file_button")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_18.setObjectName("label_18")
        self.start_test_button = QtWidgets.QPushButton(self.groupBox_5)
        self.start_test_button.setEnabled(True)
        self.start_test_button.setGeometry(QtCore.QRect(420, 360, 121, 41))
        self.start_test_button.setObjectName("start_test_button")
        self.test_camera_box = QtWidgets.QComboBox(self.groupBox_5)
        self.test_camera_box.setGeometry(QtCore.QRect(20, 220, 191, 22))
        self.test_camera_box.setObjectName("test_camera_box")
        self.label_45 = QtWidgets.QLabel(self.groupBox_5)
        self.label_45.setGeometry(QtCore.QRect(20, 200, 231, 16))
        self.label_45.setObjectName("label_45")
        self.test_model_type_box = QtWidgets.QComboBox(self.groupBox_5)
        self.test_model_type_box.setGeometry(QtCore.QRect(20, 150, 191, 22))
        self.test_model_type_box.setObjectName("test_model_type_box")
        self.test_model_type_box.addItem("")
        self.test_model_type_box.addItem("")
        self.label_46 = QtWidgets.QLabel(self.groupBox_5)
        self.label_46.setGeometry(QtCore.QRect(20, 130, 161, 16))
        self.label_46.setObjectName("label_46")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(470, 200, 31, 20))
        self.label_21.setObjectName("label_21")
        self.test_confidence_edit = QtWidgets.QLineEdit(self.groupBox_5)
        self.test_confidence_edit.setGeometry(QtCore.QRect(370, 150, 231, 21))
        self.test_confidence_edit.setCursorPosition(3)
        self.test_confidence_edit.setObjectName("test_confidence_edit")
        self.test_iou_edit = QtWidgets.QLineEdit(self.groupBox_5)
        self.test_iou_edit.setGeometry(QtCore.QRect(370, 220, 231, 21))
        self.test_iou_edit.setCursorPosition(3)
        self.test_iou_edit.setObjectName("test_iou_edit")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(450, 130, 71, 16))
        self.label_20.setObjectName("label_20")
        self.Tabs.addTab(self.Train, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Motion Control"))
        self.Main.setToolTip(_translate("MainWindow", "<html><head/><body><p>Главная</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Настройка команд"))
        self.label.setText(_translate("MainWindow", "Путь к json-файлу с командами:"))
        self.get_commands_file_button.setText(_translate("MainWindow", "Открыть"))
        self.create_commands_file_button.setText(_translate("MainWindow", "Создать"))
        self.label_2.setText(_translate("MainWindow", "Жест"))
        self.gesture_box.setItemText(0, _translate("MainWindow", "like"))
        self.gesture_box.setItemText(1, _translate("MainWindow", "dislike"))
        self.gesture_box.setItemText(2, _translate("MainWindow", "one"))
        self.gesture_box.setItemText(3, _translate("MainWindow", "peace"))
        self.gesture_box.setItemText(4, _translate("MainWindow", "peace_inverted"))
        self.gesture_box.setItemText(5, _translate("MainWindow", "three"))
        self.gesture_box.setItemText(6, _translate("MainWindow", "four"))
        self.gesture_box.setItemText(7, _translate("MainWindow", "palm"))
        self.gesture_box.setItemText(8, _translate("MainWindow", "grabbing"))
        self.gesture_box.setItemText(9, _translate("MainWindow", "fist"))
        self.gesture_box.setItemText(10, _translate("MainWindow", "grip"))
        self.gesture_box.setItemText(11, _translate("MainWindow", "point"))
        self.gesture_box.setItemText(12, _translate("MainWindow", "three3"))
        self.gesture_box.setItemText(13, _translate("MainWindow", "three2"))
        self.gesture_box.setItemText(14, _translate("MainWindow", "little_finger"))
        self.gesture_box.setItemText(15, _translate("MainWindow", "middle_finger"))
        self.gesture_box.setItemText(16, _translate("MainWindow", "ok"))
        self.gesture_box.setItemText(17, _translate("MainWindow", "rock"))
        self.gesture_box.setItemText(18, _translate("MainWindow", "call"))
        self.gesture_box.setItemText(19, _translate("MainWindow", "stop"))
        self.gesture_box.setItemText(20, _translate("MainWindow", "stop_inverted"))
        self.gesture_box.setItemText(21, _translate("MainWindow", "two_up"))
        self.gesture_box.setItemText(22, _translate("MainWindow", "two_up_inverted"))
        self.gesture_box.setItemText(23, _translate("MainWindow", "three_gun"))
        self.gesture_box.setItemText(24, _translate("MainWindow", "thumb_index"))
        self.gesture_box.setItemText(25, _translate("MainWindow", "thumb_index2"))
        self.gesture_box.setItemText(26, _translate("MainWindow", "holy"))
        self.gesture_box.setItemText(27, _translate("MainWindow", "timeout"))
        self.gesture_box.setItemText(28, _translate("MainWindow", "xsign"))
        self.gesture_box.setItemText(29, _translate("MainWindow", "hand_heart"))
        self.gesture_box.setItemText(30, _translate("MainWindow", "hand_heart2"))
        self.gesture_box.setItemText(31, _translate("MainWindow", "take_picture"))
        self.gesture_box.setItemText(32, _translate("MainWindow", "mute"))
        self.label_3.setText(_translate("MainWindow", "Путь к скрипту"))
        self.get_script_file_button.setText(_translate("MainWindow", "Открыть"))
        self.save_command_button.setText(_translate("MainWindow", "Сохранить команду"))
        self.label_24.setText(_translate("MainWindow", "→"))
        self.delete_commands_button.setText(_translate("MainWindow", "Удалить команду"))
        self.show_commands_button.setText(_translate("MainWindow", "Показать все команды"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Настройка детектора"))
        self.label_4.setText(_translate("MainWindow", "Путь к чекпоинту:"))
        self.get_main_chkpt_button.setText(_translate("MainWindow", "Открыть"))
        self.main_model_type_box.setItemText(0, _translate("MainWindow", "YOLO"))
        self.main_model_type_box.setItemText(1, _translate("MainWindow", "SSDLite"))
        self.label_5.setText(_translate("MainWindow", "Вид модели:"))
        self.label_7.setText(_translate("MainWindow", "Confidence"))
        self.main_confidence_edit.setInputMask(_translate("MainWindow", "B.999999"))
        self.main_confidence_edit.setText(_translate("MainWindow", "0.5"))
        self.main_iou_edit.setInputMask(_translate("MainWindow", "B.999999"))
        self.main_iou_edit.setText(_translate("MainWindow", "0.5"))
        self.label_8.setText(_translate("MainWindow", "IoU"))
        self.label_6.setText(_translate("MainWindow", "Выбор видеокамеры:"))
        self.start_app_button.setText(_translate("MainWindow", "Старт"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Main), _translate("MainWindow", "Главная"))
        self.label_9.setText(_translate("MainWindow", "Путь к папке с данными:"))
        self.get_data_save_folder_button.setText(_translate("MainWindow", "Открыть"))
        self.label_10.setText(_translate("MainWindow", "Выбор видеокамеры:"))
        self.get_photo_button.setText(_translate("MainWindow", "Сделать фото"))
        self.timer_edit.setInputMask(_translate("MainWindow", "9"))
        self.timer_edit.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "Таймер:"))
        self.use_camera_button.setText(_translate("MainWindow", "Включить камеру"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Камера"))
        self.cancel_photo_button.setText(_translate("MainWindow", "Отмена"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Data), _translate("MainWindow", "Данные"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Параметры обучения"))
        self.start_train_button.setText(_translate("MainWindow", "Начать обучение"))
        self.get_data_train_folder_button.setText(_translate("MainWindow", "Открыть"))
        self.train_model_type_box.setItemText(0, _translate("MainWindow", "YOLO"))
        self.train_model_type_box.setItemText(1, _translate("MainWindow", "SSDLite"))
        self.label_16.setText(_translate("MainWindow", "Вид модели:"))
        self.label_11.setText(_translate("MainWindow", "Путь к папке с данными:"))
        self.label_17.setText(_translate("MainWindow", "Количество эпох:"))
        self.epochs_edit.setInputMask(_translate("MainWindow", "D9999999999999999999"))
        self.epochs_edit.setText(_translate("MainWindow", "1"))
        self.get_start_chkpt_file_button.setText(_translate("MainWindow", "Открыть"))
        self.label_15.setText(_translate("MainWindow", "Путь к стартовому чекпойнту:"))
        self.create_end_chkpt_file_button.setText(_translate("MainWindow", "Выбрать"))
        self.label_23.setText(_translate("MainWindow", "Путь к новому чекпойнту:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Результаты тестирования"))
        self.get_test_chkpt_file_button.setText(_translate("MainWindow", "Открыть"))
        self.label_18.setText(_translate("MainWindow", "Путь к чекпойнту:"))
        self.start_test_button.setText(_translate("MainWindow", "Тестирование"))
        self.label_45.setText(_translate("MainWindow", "Выбор видеокамеры:"))
        self.test_model_type_box.setItemText(0, _translate("MainWindow", "YOLO"))
        self.test_model_type_box.setItemText(1, _translate("MainWindow", "SSDLite"))
        self.label_46.setText(_translate("MainWindow", "Вид тестируемой модели:"))
        self.label_21.setText(_translate("MainWindow", "IoU"))
        self.test_confidence_edit.setInputMask(_translate("MainWindow", "B.999999"))
        self.test_confidence_edit.setText(_translate("MainWindow", "0.5"))
        self.test_iou_edit.setInputMask(_translate("MainWindow", "B.999999"))
        self.test_iou_edit.setText(_translate("MainWindow", "0.5"))
        self.label_20.setText(_translate("MainWindow", "Confidence"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Train), _translate("MainWindow", "Обучение модели"))

