# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 819)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(0, 0, 1001, 771))
        self.Tabs.setObjectName("Tabs")
        self.Main = QtWidgets.QWidget()
        self.Main.setObjectName("Main")
        self.groupBox = QtWidgets.QGroupBox(self.Main)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 991, 291))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(30, 60, 711, 21))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 241, 20))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(880, 50, 81, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(770, 50, 81, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 241, 20))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(30, 110, 231, 101))
        self.comboBox.setMaxVisibleItems(5)
        self.comboBox.setIconSize(QtCore.QSize(100, 100))
        self.comboBox.setObjectName("comboBox")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/grabbing.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/grip.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/holy.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/point.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/call.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/three3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/timeout.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/xsign.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/hand_heart.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/hand_heart2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon9, "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/little_finger.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon10, "")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/middle_finger.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon11, "")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/take_picture.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon12, "")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/dislike.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon13, "")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/fist.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon14, "")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/four.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon15, "")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icons/like.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon16, "")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("icons/mute.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon17, "")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("icons/ok.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon18, "")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("icons/one.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon19, "")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("icons/palm.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon20, "")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("icons/peace.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon21, "")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("icons/peace_inverted.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon22, "")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("icons/rock.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon23, "")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("icons/stop.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon24, "")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("icons/stop_inverted.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon25, "")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("icons/three.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon26, "")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("icons/three2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon27, "")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap("icons/two_up.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon28, "")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap("icons/two_up_inverted.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon29, "")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("icons/three_gun.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon30, "")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap("icons/thumb_index.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon31, "")
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap("icons/thumb_index2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon32, "")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(340, 120, 231, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 150, 511, 21))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(880, 140, 81, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 230, 151, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(280, 130, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_24.setFont(font)
        self.label_24.setLineWidth(2)
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_19.setGeometry(QtCore.QRect(610, 230, 151, 41))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_20.setGeometry(QtCore.QRect(430, 230, 151, 41))
        self.pushButton_20.setObjectName("pushButton_20")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Main)
        self.groupBox_2.setGeometry(QtCore.QRect(-1, 289, 991, 471))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 50, 571, 21))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(280, 30, 231, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(880, 40, 81, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(40, 50, 191, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(40, 30, 231, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(470, 140, 71, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(400, 160, 231, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(710, 160, 231, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(820, 140, 31, 20))
        self.label_8.setObjectName("label_8")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setGeometry(QtCore.QRect(40, 160, 191, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(40, 140, 231, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(410, 300, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.Tabs.addTab(self.Main, "")
        self.Data = QtWidgets.QWidget()
        self.Data.setObjectName("Data")
        self.label_9 = QtWidgets.QLabel(self.Data)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 151, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.Data)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 40, 811, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.Data)
        self.pushButton_8.setGeometry(QtCore.QRect(850, 30, 81, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.comboBox_4 = QtWidgets.QComboBox(self.Data)
        self.comboBox_4.setGeometry(QtCore.QRect(250, 90, 191, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_10 = QtWidgets.QLabel(self.Data)
        self.label_10.setGeometry(QtCore.QRect(250, 70, 231, 16))
        self.label_10.setObjectName("label_10")
        self.pushButton_10 = QtWidgets.QPushButton(self.Data)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setGeometry(QtCore.QRect(450, 670, 121, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.Data)
        self.lineEdit_8.setGeometry(QtCore.QRect(360, 680, 71, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_14 = QtWidgets.QLabel(self.Data)
        self.label_14.setGeometry(QtCore.QRect(300, 680, 51, 16))
        self.label_14.setObjectName("label_14")
        self.pushButton_18 = QtWidgets.QPushButton(self.Data)
        self.pushButton_18.setEnabled(True)
        self.pushButton_18.setGeometry(QtCore.QRect(560, 80, 131, 41))
        self.pushButton_18.setObjectName("pushButton_18")
        self.groupBox_7 = QtWidgets.QGroupBox(self.Data)
        self.groupBox_7.setGeometry(QtCore.QRect(180, 130, 681, 531))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_25 = QtWidgets.QLabel(self.groupBox_7)
        self.label_25.setGeometry(QtCore.QRect(19, 30, 640, 480))
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.pushButton_37 = QtWidgets.QPushButton(self.Data)
        self.pushButton_37.setEnabled(False)
        self.pushButton_37.setGeometry(QtCore.QRect(600, 670, 121, 41))
        self.pushButton_37.setObjectName("pushButton_37")
        self.Tabs.addTab(self.Data, "")
        self.Train = QtWidgets.QWidget()
        self.Train.setObjectName("Train")
        self.groupBox_4 = QtWidgets.QGroupBox(self.Train)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 971, 371))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_13.setGeometry(QtCore.QRect(410, 300, 131, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_11.setGeometry(QtCore.QRect(860, 40, 81, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_6.setGeometry(QtCore.QRect(20, 100, 191, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(20, 80, 231, 16))
        self.label_16.setObjectName("label_16")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(20, 30, 151, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_9.setGeometry(QtCore.QRect(260, 100, 561, 22))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(20, 140, 111, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(20, 160, 101, 22))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_12.setGeometry(QtCore.QRect(860, 90, 81, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(260, 80, 191, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(20, 50, 801, 22))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_16.setGeometry(QtCore.QRect(260, 230, 561, 22))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_16.setGeometry(QtCore.QRect(860, 220, 81, 41))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(260, 210, 191, 16))
        self.label_23.setObjectName("label_23")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_7.setGeometry(QtCore.QRect(20, 230, 191, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(20, 210, 161, 16))
        self.label_22.setObjectName("label_22")
        self.groupBox_5 = QtWidgets.QGroupBox(self.Train)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 380, 971, 371))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_12.setGeometry(QtCore.QRect(20, 80, 801, 22))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_14.setGeometry(QtCore.QRect(860, 70, 81, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_18.setObjectName("label_18")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_17.setEnabled(True)
        self.pushButton_17.setGeometry(QtCore.QRect(420, 280, 121, 41))
        self.pushButton_17.setObjectName("pushButton_17")
        self.comboBox_13 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_13.setGeometry(QtCore.QRect(20, 220, 191, 22))
        self.comboBox_13.setObjectName("comboBox_13")
        self.label_45 = QtWidgets.QLabel(self.groupBox_5)
        self.label_45.setGeometry(QtCore.QRect(20, 200, 231, 16))
        self.label_45.setObjectName("label_45")
        self.comboBox_14 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_14.setGeometry(QtCore.QRect(20, 150, 191, 22))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.label_46 = QtWidgets.QLabel(self.groupBox_5)
        self.label_46.setGeometry(QtCore.QRect(20, 130, 161, 16))
        self.label_46.setObjectName("label_46")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(470, 200, 31, 20))
        self.label_21.setObjectName("label_21")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_15.setGeometry(QtCore.QRect(370, 150, 231, 21))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_14.setGeometry(QtCore.QRect(370, 220, 231, 21))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(450, 130, 71, 16))
        self.label_20.setObjectName("label_20")
        self.Tabs.addTab(self.Train, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Main.setToolTip(_translate("MainWindow", "<html><head/><body><p>Главная</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Настройка команд"))
        self.label.setText(_translate("MainWindow", "Путь к json-файлу с командами:"))
        self.pushButton.setText(_translate("MainWindow", "Открыть"))
        self.pushButton_2.setText(_translate("MainWindow", "Создать"))
        self.label_2.setText(_translate("MainWindow", "Жест"))
        self.comboBox.setItemText(0, _translate("MainWindow", "grabbing"))
        self.comboBox.setItemText(1, _translate("MainWindow", "grip"))
        self.comboBox.setItemText(2, _translate("MainWindow", "holy"))
        self.comboBox.setItemText(3, _translate("MainWindow", "point"))
        self.comboBox.setItemText(4, _translate("MainWindow", "call"))
        self.comboBox.setItemText(5, _translate("MainWindow", "three3"))
        self.comboBox.setItemText(6, _translate("MainWindow", "timeout"))
        self.comboBox.setItemText(7, _translate("MainWindow", "xsign"))
        self.comboBox.setItemText(8, _translate("MainWindow", "hand_heart"))
        self.comboBox.setItemText(9, _translate("MainWindow", "hand_heart2"))
        self.comboBox.setItemText(10, _translate("MainWindow", "little_finger"))
        self.comboBox.setItemText(11, _translate("MainWindow", "middle_finger"))
        self.comboBox.setItemText(12, _translate("MainWindow", "take_picture"))
        self.comboBox.setItemText(13, _translate("MainWindow", "dislike"))
        self.comboBox.setItemText(14, _translate("MainWindow", "fist"))
        self.comboBox.setItemText(15, _translate("MainWindow", "four"))
        self.comboBox.setItemText(16, _translate("MainWindow", "like"))
        self.comboBox.setItemText(17, _translate("MainWindow", "mute"))
        self.comboBox.setItemText(18, _translate("MainWindow", "ok"))
        self.comboBox.setItemText(19, _translate("MainWindow", "one"))
        self.comboBox.setItemText(20, _translate("MainWindow", "palm"))
        self.comboBox.setItemText(21, _translate("MainWindow", "peace"))
        self.comboBox.setItemText(22, _translate("MainWindow", "peace_inverted"))
        self.comboBox.setItemText(23, _translate("MainWindow", "rock"))
        self.comboBox.setItemText(24, _translate("MainWindow", "stop"))
        self.comboBox.setItemText(25, _translate("MainWindow", "stop_inverted"))
        self.comboBox.setItemText(26, _translate("MainWindow", "three"))
        self.comboBox.setItemText(27, _translate("MainWindow", "three2"))
        self.comboBox.setItemText(28, _translate("MainWindow", "two_up"))
        self.comboBox.setItemText(29, _translate("MainWindow", "two_up_inverted"))
        self.comboBox.setItemText(30, _translate("MainWindow", "three_gun"))
        self.comboBox.setItemText(31, _translate("MainWindow", "thumb_index"))
        self.comboBox.setItemText(32, _translate("MainWindow", "thumb_index2"))
        self.label_3.setText(_translate("MainWindow", "Путь к скрипту"))
        self.pushButton_4.setText(_translate("MainWindow", "Открыть"))
        self.pushButton_5.setText(_translate("MainWindow", "Сохранить команду"))
        self.label_24.setText(_translate("MainWindow", "→"))
        self.pushButton_19.setText(_translate("MainWindow", "Удалить команду"))
        self.pushButton_20.setText(_translate("MainWindow", "Показать все команды"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Настройка детектора"))
        self.label_4.setText(_translate("MainWindow", "Путь к чекпоинту:"))
        self.pushButton_6.setText(_translate("MainWindow", "Открыть"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "YOLO"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "SSDLite"))
        self.label_5.setText(_translate("MainWindow", "Вид модели:"))
        self.label_7.setText(_translate("MainWindow", "Confidence"))
        self.lineEdit_4.setText(_translate("MainWindow", "0.5"))
        self.lineEdit_5.setText(_translate("MainWindow", "0.5"))
        self.label_8.setText(_translate("MainWindow", "IoU"))
        self.label_6.setText(_translate("MainWindow", "Выбор видеокамеры:"))
        self.pushButton_7.setText(_translate("MainWindow", "Старт"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Main), _translate("MainWindow", "Главная"))
        self.label_9.setText(_translate("MainWindow", "Путь к папке с данными:"))
        self.pushButton_8.setText(_translate("MainWindow", "Открыть"))
        self.label_10.setText(_translate("MainWindow", "Выбор видеокамеры:"))
        self.pushButton_10.setText(_translate("MainWindow", "Сделать фото"))
        self.lineEdit_8.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "Таймер:"))
        self.pushButton_18.setText(_translate("MainWindow", "Включить камеру"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Камера"))
        self.pushButton_37.setText(_translate("MainWindow", "Отмена"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Data), _translate("MainWindow", "Данные"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Параметры обучения"))
        self.pushButton_13.setText(_translate("MainWindow", "Начать обучение"))
        self.pushButton_11.setText(_translate("MainWindow", "Открыть"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "YOLO"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "SSDLite"))
        self.label_16.setText(_translate("MainWindow", "Вид модели:"))
        self.label_11.setText(_translate("MainWindow", "Путь к папке с данными:"))
        self.label_17.setText(_translate("MainWindow", "Количество эпох:"))
        self.lineEdit_11.setText(_translate("MainWindow", "1"))
        self.pushButton_12.setText(_translate("MainWindow", "Открыть"))
        self.label_15.setText(_translate("MainWindow", "Путь к стартовому чекпойнту:"))
        self.pushButton_16.setText(_translate("MainWindow", "Открыть"))
        self.label_23.setText(_translate("MainWindow", "Путь к новому чекпойнту:"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "YOLO"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "SSDLite"))
        self.label_22.setText(_translate("MainWindow", "Вид сохраняемой модели:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Результаты тестирования"))
        self.pushButton_14.setText(_translate("MainWindow", "Открыть"))
        self.label_18.setText(_translate("MainWindow", "Путь к чекпойнту:"))
        self.pushButton_17.setText(_translate("MainWindow", "Тестирование"))
        self.label_45.setText(_translate("MainWindow", "Выбор видеокамеры:"))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "YOLO"))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "SSDLite"))
        self.label_46.setText(_translate("MainWindow", "Вид тестируемой модели:"))
        self.label_21.setText(_translate("MainWindow", "IoU"))
        self.lineEdit_15.setText(_translate("MainWindow", "0.5"))
        self.lineEdit_14.setText(_translate("MainWindow", "0.5"))
        self.label_20.setText(_translate("MainWindow", "Confidence"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Train), _translate("MainWindow", "Обучение модели"))

